version: '2'
services:
    ninjabid-app:
        image: ninjabid
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ninjabid-postgresql:5432/ninjabid
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ninjabid-elasticsearch:9300
        ports:
            - 8080:8080
    ninjabid-postgresql:
        extends:
            file: postgresql.yml
            service: ninjabid-postgresql
    ninjabid-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ninjabid-elasticsearch
